dependencies:
  - underscore-1.8.3
  - backbone-1.2.1

tasks:
  graspi_build:
    - graspi_js_copy
    - graspi_js_concat

options:
  basePath: 'bower_components/backbone.babysitter/lib'
  destFolder: 'backbone.babysitter'
  js:
    destFile: 'backbone.babysitter.js'
    files:
      - 'backbone.babysitter.js'