dependencies: []

tasks:
  graspi_build:
    - graspi_js_copy
    - graspi_js_concat

options:
  basePath: 'bower_components/requirejs'
  destPath: 'tmp/graspi/build/requirejs'
  js:
    destFile: 'require.js'
    files:
      - 'require.js'