dependencies: []

tasks:
  graspi_build:
    - graspi_js_copy
    - graspi_js_concat

options:
  basePath: 'bower_components/underscore'
  destFolder: 'underscore'
  js:
    destFile: 'underscore.js'
    files:
      - 'underscore.js'