# tmp folder for modules
tmpPath: 'tmp/graspi/staging'

# graspi tasks cache file
# cacheFile: 'tmp/graspi/files_cache_register.json'

# graspi tasks built track file
# modulesBuiltTrackFile: 'tmp/graspi/modules_built_track_register.json'


# ------------------------------------------------------
# css
# ------------------------------------------------------
css:
  # grunt-concat-sourcemap
  concat:
    cached:             false
  # grunt-contrib-copy
  copy:
    cached:             false
  # grunt-contrib-sass
  sass:
    cached:             false
    options:
      sourcemap:          'auto'
      trace:              false
      style:              'nested'
      precision:          10
      debugInfo:          false
      lineNumbers:        false
      noCache:            true
      bundleExec:         true
      update:             false
  # grunt-contrib-less
  less:
    cached:             false
    options:
      compress:           false
      sourceMap:          true
  # grunt-contrib-cssmin and clean-css
  minify:
    cached:             false
    report:             'gzip'
    sourceMap:          true
    # clean-css
    options:
      advanced:               false
      aggressiveMerging:      false
      compatibility:          '*'
      keepBreaks:             false
      keepSpecialComments:    0
      mediaMerging:           true
      rebase:                 false
      restructuring:          true
      roundingPrecision:      -1

# ------------------------------------------------------
# js
# ------------------------------------------------------
js:
  # grunt-concat-sourcemap
  copy:
    cached:             false
  # grunt-concat-sourcemap
  concat:
    cached:             false
    includeDependencies: false
  # grunt-contrib-coffee
  coffee:
    cached:             false
    options:
      sourceMap:          true
  # grunt-contrib-uglify
  uglify:
    cached:             false
    options:
      beautify:           false
      expression:         false
      report:             'gzip'
      sourceMap:          true
      preserveComments:   'all'

# ------------------------------------------------------
# images
# ------------------------------------------------------
images:
  # grunt-contrib-copy
  copy:
    cached:             false
  # grunt-contrib-imagemin
  imagemin:
    cached:             false
    options:
      gifInterlaced:          true
      jpegProgressive:        true
      pngOptimizationLevel:   3
    usePlugins:
      - jpegRecompressPlugin
    plugins:
      # imagemin-jpeg-recompress
      jpegRecompressPlugin:
        loops:          6
        accurate:       true
        quality:        'high'
        method:         'ssim'
        target:         0.8
        min:            70
        max:            90
        defish:         0
        progressive:    true
        subsample:      'default'

# ------------------------------------------------------
# fonts
# ------------------------------------------------------
fonts:
  # grunt-contrib-copy
  copy:
    cached:             false

# ------------------------------------------------------
# postpipeline
# ------------------------------------------------------
postpipeline:
  # custom implementation
  filerevision:
    digest:       true
    cached:       false
  # custom implementation
  manifest:
    cached:       false
  # custom implementation
  urlReplace:
    cached:       false

